apiVersion: v1
kind: Secret
metadata:
  name: wp-config
data:
  wp-config.php: |
    PD9waHAKLyoqCiAqIFRoZSBiYXNlIGNvbmZpZ3VyYXRpb24gZm9yIFdvcmRQcmVzcwogKgogKiBU
    aGUgd3AtY29uZmlnLnBocCBjcmVhdGlvbiBzY3JpcHQgdXNlcyB0aGlzIGZpbGUgZHVyaW5nIHRo
    ZSBpbnN0YWxsYXRpb24uCiAqIFlvdSBkb24ndCBoYXZlIHRvIHVzZSB0aGUgd2ViIHNpdGUsIHlv
    dSBjYW4gY29weSB0aGlzIGZpbGUgdG8gIndwLWNvbmZpZy5waHAiCiAqIGFuZCBmaWxsIGluIHRo
    ZSB2YWx1ZXMuCiAqCiAqIFRoaXMgZmlsZSBjb250YWlucyB0aGUgZm9sbG93aW5nIGNvbmZpZ3Vy
    YXRpb25zOgogKgogKiAqIERhdGFiYXNlIHNldHRpbmdzCiAqICogU2VjcmV0IGtleXMKICogKiBE
    YXRhYmFzZSB0YWJsZSBwcmVmaXgKICogKiBMb2NhbGl6ZWQgbGFuZ3VhZ2UKICogKiBBQlNQQVRI
    CiAqCiAqIEBsaW5rIGh0dHBzOi8vd29yZHByZXNzLm9yZy9zdXBwb3J0L2FydGljbGUvZWRpdGlu
    Zy13cC1jb25maWctcGhwLwogKgogKiBAcGFja2FnZSBXb3JkUHJlc3MKICovCgovLyAqKiBEYXRh
    YmFzZSBzZXR0aW5ncyAtIFlvdSBjYW4gZ2V0IHRoaXMgaW5mbyBmcm9tIHlvdXIgd2ViIGhvc3Qg
    KiogLy8KLyoqIFRoZSBuYW1lIG9mIHRoZSBkYXRhYmFzZSBmb3IgV29yZFByZXNzICovCmRlZmlu
    ZSggJ0RCX05BTUUnLCAnd29yZHByZXNzJyApOwoKLyoqIERhdGFiYXNlIHVzZXJuYW1lICovCmRl
    ZmluZSggJ0RCX1VTRVInLCAnd29yZHByZXNzJyApOwoKLyoqIERhdGFiYXNlIHBhc3N3b3JkICov
    CmRlZmluZSggJ0RCX1BBU1NXT1JEJywgJ01hcmlhREIxMSEnICk7CgovKiogRGF0YWJhc2UgaG9z
    dG5hbWUgKi8KZGVmaW5lKCAnREJfSE9TVCcsICdtYXJpYWRiLWdhbGVyYScgKTsKCi8qKiBEYXRh
    YmFzZSBjaGFyc2V0IHRvIHVzZSBpbiBjcmVhdGluZyBkYXRhYmFzZSB0YWJsZXMuICovCmRlZmlu
    ZSggJ0RCX0NIQVJTRVQnLCAndXRmOCcgKTsKCi8qKiBUaGUgZGF0YWJhc2UgY29sbGF0ZSB0eXBl
    LiBEb24ndCBjaGFuZ2UgdGhpcyBpZiBpbiBkb3VidC4gKi8KZGVmaW5lKCAnREJfQ09MTEFURScs
    ICcnICk7CgovKiojQCsKICogQXV0aGVudGljYXRpb24gdW5pcXVlIGtleXMgYW5kIHNhbHRzLgog
    KgogKiBDaGFuZ2UgdGhlc2UgdG8gZGlmZmVyZW50IHVuaXF1ZSBwaHJhc2VzISBZb3UgY2FuIGdl
    bmVyYXRlIHRoZXNlIHVzaW5nCiAqIHRoZSB7QGxpbmsgaHR0cHM6Ly9hcGkud29yZHByZXNzLm9y
    Zy9zZWNyZXQta2V5LzEuMS9zYWx0LyBXb3JkUHJlc3Mub3JnIHNlY3JldC1rZXkgc2VydmljZX0u
    CiAqCiAqIFlvdSBjYW4gY2hhbmdlIHRoZXNlIGF0IGFueSBwb2ludCBpbiB0aW1lIHRvIGludmFs
    aWRhdGUgYWxsIGV4aXN0aW5nIGNvb2tpZXMuCiAqIFRoaXMgd2lsbCBmb3JjZSBhbGwgdXNlcnMg
    dG8gaGF2ZSB0byBsb2cgaW4gYWdhaW4uCiAqCiAqIEBzaW5jZSAyLjYuMAogKi8KZGVmaW5lKCAn
    QVVUSF9LRVknLCAgICAgICAgICAnfFAjeiBtUXg9WnxdKTFIRDM0QyE2O2AgbE1KIyooPVMmfGQu
    Umt0RCA8QEhHVHl1aVczOy5MQjtxckpkMHxvOScgKTsKZGVmaW5lKCAnU0VDVVJFX0FVVEhfS0VZ
    JywgICAnLk5eVWlBTUVXRGY0Xl9WWSQzIVdSNS5RbiYtUj9hPWUmKGJ1Yld4dilPVSlufmheNCZT
    ckQsWncoRyRtV1oqRycgKTsKZGVmaW5lKCAnTE9HR0VEX0lOX0tFWScsICAgICAnYSN+fndhOWZN
    RShFeSk+MyZnbS0xeTliWlApWit+XihOKyUwOUNgbFJCW3lQalR0UWdMfUFRXT4sIUAle3J6IScg
    KTsKZGVmaW5lKCAnTk9OQ0VfS0VZJywgICAgICAgICAndXVpcm5FMlAhb1J+fSZVcEV6RFpuIShZ
    UT5tb21FT2taaTx3VlhAWEs8aDssfk5JJltxdm5PMi9zLkhfO2h7dycgKTsKZGVmaW5lKCAnQVVU
    SF9TQUxUJywgICAgICAgICAnL0V2PkpxVjZ9MWd7UF9rdUwgJi16bTpRUXMsWCEsflc9MmkjYWJ5
    RjxJVGwqYX42Mk5ZU1ZqYko0TklBXXwzZCcgKTsKZGVmaW5lKCAnU0VDVVJFX0FVVEhfU0FMVCcs
    ICAnaW1Ib0cyOU9sQy5fO1FeOGcqTVo4aFJmQkorWFJwem1AUUtHSFh+TFM7PmQ9PCZ7ZXFOSmcr
    bzZ0WWZGNWRHcCcgKTsKZGVmaW5lKCAnTE9HR0VEX0lOX1NBTFQnLCAgICAnOFcrLn4sVzt9WTM0
    dy9mUWxlKUBVRkRBe2Z3PjM4O0ldRHI3Mk1vMjpuQjQ/STs/cld2TDtfdWZqRmhdWTBySScgKTsK
    ZGVmaW5lKCAnTk9OQ0VfU0FMVCcsICAgICAgICAnTnE2b0t3PGBAOF1zVGQpWlJ8ZEgoaXlYelYu
    IzRJeTZTbC8sZDRyfmxwP145PiZZaEVAJmcsOWwpMnNXM2UjSicgKTsKZGVmaW5lKCAnV1BfQ0FD
    SEVfS0VZX1NBTFQnLCAnQk9sciVaZTl3fmpkTF0kUSxPRnMhL05hRkVlMGdefF5lT35DSF5vTmVW
    VExXLm49NXhsK2BFRVBRNTQpLmEjdicgKTsKCgovKiojQC0qLwoKLyoqCiAqIFdvcmRQcmVzcyBk
    YXRhYmFzZSB0YWJsZSBwcmVmaXguCiAqCiAqIFlvdSBjYW4gaGF2ZSBtdWx0aXBsZSBpbnN0YWxs
    YXRpb25zIGluIG9uZSBkYXRhYmFzZSBpZiB5b3UgZ2l2ZSBlYWNoCiAqIGEgdW5pcXVlIHByZWZp
    eC4gT25seSBudW1iZXJzLCBsZXR0ZXJzLCBhbmQgdW5kZXJzY29yZXMgcGxlYXNlIQogKi8KJHRh
    YmxlX3ByZWZpeCA9ICd3cF8nOwoKCi8qIEFkZCBhbnkgY3VzdG9tIHZhbHVlcyBiZXR3ZWVuIHRo
    aXMgbGluZSBhbmQgdGhlICJzdG9wIGVkaXRpbmciIGxpbmUuICovCgoKCi8qKgogKiBGb3IgZGV2
    ZWxvcGVyczogV29yZFByZXNzIGRlYnVnZ2luZyBtb2RlLgogKgogKiBDaGFuZ2UgdGhpcyB0byB0
    cnVlIHRvIGVuYWJsZSB0aGUgZGlzcGxheSBvZiBub3RpY2VzIGR1cmluZyBkZXZlbG9wbWVudC4K
    ICogSXQgaXMgc3Ryb25nbHkgcmVjb21tZW5kZWQgdGhhdCBwbHVnaW4gYW5kIHRoZW1lIGRldmVs
    b3BlcnMgdXNlIFdQX0RFQlVHCiAqIGluIHRoZWlyIGRldmVsb3BtZW50IGVudmlyb25tZW50cy4K
    ICoKICogRm9yIGluZm9ybWF0aW9uIG9uIG90aGVyIGNvbnN0YW50cyB0aGF0IGNhbiBiZSB1c2Vk
    IGZvciBkZWJ1Z2dpbmcsCiAqIHZpc2l0IHRoZSBkb2N1bWVudGF0aW9uLgogKgogKiBAbGluayBo
    dHRwczovL3dvcmRwcmVzcy5vcmcvc3VwcG9ydC9hcnRpY2xlL2RlYnVnZ2luZy1pbi13b3JkcHJl
    c3MvCiAqLwppZiAoICEgZGVmaW5lZCggJ1dQX0RFQlVHJyApICkgewoJZGVmaW5lKCAnV1BfREVC
    VUcnLCBmYWxzZSApOwp9CgovKiBUaGF0J3MgYWxsLCBzdG9wIGVkaXRpbmchIEhhcHB5IHB1Ymxp
    c2hpbmcuICovCgovKiogQWJzb2x1dGUgcGF0aCB0byB0aGUgV29yZFByZXNzIGRpcmVjdG9yeS4g
    Ki8KaWYgKCAhIGRlZmluZWQoICdBQlNQQVRIJyApICkgewoJZGVmaW5lKCAnQUJTUEFUSCcsIF9f
    RElSX18gLiAnLycgKTsKfQoKLyoqIFNldHMgdXAgV29yZFByZXNzIHZhcnMgYW5kIGluY2x1ZGVk
    IGZpbGVzLiAqLwpyZXF1aXJlX29uY2UgQUJTUEFUSCAuICd3cC1zZXR0aW5ncy5waHAnOwo=